name: Update websites after push
on: push

jobs:
  update-sites:
    name: Update websites action
    runs-on: ubuntu-latest
    container: jekyll/jekyll

    steps:
      - name: Checkout member backend
        uses: actions/checkout@v2
        with:
          repository: michaelchin/bgh_atlas
          token: ${{ secrets.MY_TOKEN }}
          path: member_backend

      - name: Checkout member frontend
        uses: actions/checkout@v2
        with:
          repository: michaelchin/test_page_public
          token: ${{ secrets.MY_TOKEN }}
          path: member_frontend

      - name: Checkout public
        uses: actions/checkout@v2
        with:
          repository: michaelchin/bgh_atlas_member_public
          token: ${{ secrets.MY_TOKEN }}
          path: public
       
      - name: Update websites
        run: ./main/scripts/update-repositories.sh
        env:
          GITHUB_TOKEN: '${{secrets.MY_TOKEN}}'

