name: Update websites after push
on: push

jobs:
  build:
    name: Update websites action
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout public repo
        uses: actions/checkout@v2
        with:
          repository: michaelchin/test_page_public
          token: ${{ secrets.MY_TOKEN }}
          path: public

      - name: Checkout private repo
        uses: actions/checkout@v2
        with:
          repository: michaelchin/bgh_atlas
          token: ${{ secrets.MY_TOKEN }}
          path: private

      - name: build site
        uses: helaili/jekyll-action@2.0.3
        env:
          JEKYLL_PAT: ${{ secrets.MY_TOKEN }}
        with:
          jekyll_src: './private'

        #- name: Install Jekyll
        #run: |
        #  sudo gem install bundler jekyll
        #  sudo bundle install
      
        #- name: Build site
        #run: |
        #  cd private
        #  bundle exec jekyll build 

      - name: Moving build to artifacts directory
        run: ./main/scripts/update-repositories.sh
        env:
          GITHUB_TOKEN: '${{secrets.MY_TOKEN}}'

