name: Update websites after push
on: push

jobs:
  build:
    name: Update websites action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout public repo
        uses: actions/checkout@v2
        with:
          repository: michaelchin/test_page_public
          token: ${{ secrets.MY_TOKEN }}
          path: public

      - name: Checkout private repo
        uses: actions/checkout@v2
        with:
          repository: michaelchin/bgh_atlas
          token: ${{ secrets.MY_TOKEN }}
          path: private
       
      - name: Install Jekyll
        run: |
          echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
          echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
          echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
          gem install bundler jekyll
          bundle install
      
      - name: Build site
        run: |
          cd private
          bundle exec jekyll build 

      - name: Update websites
        run: ./main/scripts/update-repositories.sh
        env:
          GITHUB_TOKEN: '${{secrets.MY_TOKEN}}'

